Docs fixes
QuantumBFS/Yao.jl pull request #328
Opened 2022-01-23 17:16 UTC by achuchmala

* fix in-line math displaying according to suggestion in https://discourse.julialang.org/t/problem-with-inline-math-for-literate-generated-notebook/60132
* remove unnecessary lines
* fix link to Wikipedia article
* remove section about concentrator (deprecated)

2022-01-24 05:42 UTC, Roger-luo requested changes
thanks! I left a few small comments

2022-01-24 05:42 UTC, Roger-luo commented on docs/src/quick-start/2.qft-phase-estimation/main.jl
> -# a local scope of quantum circuit, and only active the first `n` qubits while applying
Why these parts are deleted?

2022-01-24 05:42 UTC, Roger-luo commented on docs/src/quick-start/2.qft-phase-estimation/main.jl
> -using Yao
I think `using Yao` is also necessary?

2022-01-24 08:40 UTC, achuchmala commented on docs/src/quick-start/2.qft-phase-estimation/main.jl
> -# a local scope of quantum circuit, and only active the first `n` qubits while applying
OK, maybe I was too fast with removing this section :/. I've done this because we don't have `concentrator` here, which is now deprecated and replaced with `subroutine`.  However now I see that `subroutine` uses `focus!` and `relax!`, so here only change of `concentrator` to `subroutine` without deleting this description should be sufficient.

2022-01-24 08:45 UTC, achuchmala commented on docs/src/quick-start/2.qft-phase-estimation/main.jl
> -using Yao
Here in the QPE circuit we need QFT, which was defined above and needed `using Yao` anyway. If we have QFT and QPE in one file, then there is no need to repeat this line.

2022-01-25 00:27 UTC, Roger-luo commented on docs/src/quick-start/2.qft-phase-estimation/main.jl
> -# a local scope of quantum circuit, and only active the first `n` qubits while applying
Yeah I see why you removed it, maybe just update the name? It's named `Subroutine` and `subroutine` now

2022-01-25 00:27 UTC, Roger-luo commented on docs/src/quick-start/2.qft-phase-estimation/main.jl
> -# a local scope of quantum circuit, and only active the first `n` qubits while applying
I think we still need a section to describe how `focus!` and `relax!` works

2022-01-25 10:05 UTC, achuchmala commented on docs/src/quick-start/2.qft-phase-estimation/main.jl
> -# a local scope of quantum circuit, and only active the first `n` qubits while applying
You are right, this description is valuable and gives some insight in how the subroutine works. Done :)

2022-01-25 17:58 UTC, Roger-luo approved these changes

2022-01-25 18:47 UTC, Roger-luo commented
Thanks you!

2022-01-25 18:47 UTC, merged