support basic error channels
QuantumBFS/Yao.jl pull request #416
Opened 2022-07-13 18:11 UTC by Roger-luo

2022-07-13 18:28 UTC, GiggleLiu requested changes

2022-07-13 18:28 UTC, GiggleLiu commented on lib/YaoAPI/src/registers.jl
> -    DensityMatrix{D,T,MT<:AbstractMatrix{T}} <: AbstractRegister{D}
Why do you move DensityMatrix out from YaoAPI? I think it will be convenient for developers to extend if we put it here.

2022-07-13 18:28 UTC, GiggleLiu commented on lib/YaoArrayRegister/src/density_matrix.jl
> +    N = nlevel^n
```julia
julia> rand_density_matrix(ComplexF64, 3)
DensityMatrix{2, Float64, Matrix{Float64}}([0.09895989446363539 0.033083525024186204 … 0.024417543183544423 0.0015611307789331337; 0.033083525024186225 0.09796262397994808 … -0.01405934647515636 -0.009407688198002211; … ; 0.024417543183544395 -0.014059346475156385 … 0.152166399588001 -0.018906510990330864; 0.0015611307789331207 -0.00940768819800221 … -0.018906510990330857 0.13113192677153102])
```

Data type is not correct. Why don't we just do
```julia
partial_tr(density_matrix(rand_state(6; nlevel=2)), (1,2,3))
```

2022-07-13 18:28 UTC, GiggleLiu commented on lib/YaoBlocks/src/channel/error.jl
> +    opX = repeat(n, X, locs)
bit flip channel is single bit flip channel right? this error channel flips all bits. I guess this is wrong?

2022-07-13 18:28 UTC, GiggleLiu commented on lib/YaoBlocks/src/channel/error.jl
> +    opZ = repeat(n, Z, locs)
The same here.

2022-07-13 18:28 UTC, GiggleLiu commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
The same here, I think we need to have a location parameter to specify which qubits have such error.

2022-07-13 18:32 UTC, Roger-luo commented on lib/YaoAPI/src/registers.jl
> -    DensityMatrix{D,T,MT<:AbstractMatrix{T}} <: AbstractRegister{D}
this is causing type piracy in `YaoArrayRegister`

2022-07-13 18:34 UTC, Roger-luo commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
The depolarizing channel doesn't have a location by definition tho. It's just adding identity to the entire density matrix.

2022-07-13 18:34 UTC, GiggleLiu commented on lib/YaoAPI/src/registers.jl
> -    DensityMatrix{D,T,MT<:AbstractMatrix{T}} <: AbstractRegister{D}
Yeah, this can not be avoided right, we already choose such design pattern.
I guess we have a lot other piracy already.

2022-07-13 18:36 UTC, GiggleLiu commented on lib/YaoArrayRegister/src/density_matrix.jl
> +    N = nlevel^n
Why it causes too much memory? It might be a bug in `partial_tr`

2022-07-13 18:52 UTC, Roger-luo commented on lib/YaoArrayRegister/src/density_matrix.jl
> +    N = nlevel^n
I think you are right, change it back

2022-07-14 02:19 UTC, GiggleLiu commented on lib/YaoAPI/src/registers.jl
> -    DensityMatrix{D,T,MT<:AbstractMatrix{T}} <: AbstractRegister{D}
> I don't see anyone is using YaoAPI to extend density matrix after all

The same reason applies here: I don't see anyone is suffering from this type of piracy. DM is just general purposed, we hope whoever what to extend Yao's density matrix can have a very light weighted API package to extend. This is the purpose of YaoAPI. We allow piracy because we consider YaoAPI as kind of Yao's submodule. The piracy here is not a problem because we do not implement any function on DM type in the API package.

2022-07-14 02:26 UTC, GiggleLiu commented on lib/YaoBlocks/src/channel/error.jl
> +    return map(0:1<<total-1) do syndrome
I am not sure you have to create exponential many syndromes. Can we do it in a more clever way?

2022-07-14 02:37 UTC, GiggleLiu commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
If you add a `locs` argument, you can decide which qubit has the depolarizing error. Then their state will become completely mixed. No?

2022-07-14 02:37 UTC, GiggleLiu commented on lib/YaoBlocks/test/channel/error.jl
> +using Test
I guess you forgot to include this file in tests.

2022-07-14 15:00 UTC, Roger-luo commented on lib/YaoBlocks/src/channel/error.jl
> +    return map(0:1<<total-1) do syndrome
This is during construction and only exponential on number of locations. This has no difference with applying a list of channels. I think this is more convenient.

2022-07-14 15:01 UTC, Roger-luo commented on lib/YaoBlocks/src/channel/error.jl
> +    return map(0:1<<total-1) do syndrome
kron of list of unitary channels is more costly than just compose them into one.

2022-07-14 17:06 UTC, GiggleLiu commented on lib/YaoAPI/src/registers.jl
> -    DensityMatrix{D,T,MT<:AbstractMatrix{T}} <: AbstractRegister{D}
Interesting, I want to hear more about the method saving mechanism in Julia. Let us discuss in person.

2023-02-14 15:36 UTC, jlbosse commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
There is indeed a sensible definition of a multi-qubit depolarizing channel 
and it can be written down as a unitary channel as follows:
$$
  ρ ↦ (1-p) ρ + p/(2^k - 1) ∑_{P_k ≠ id} P_k ρ P_k
$$
where the sum runs over all non-identity Pauli-strings acting on qubits 1
to k and ρ is a n-qubit density matrix. For simplicity, I assumed that we want 
the depolarizing channel on the first k qubits, but it should be clear how 
this definition extends to the general case where we want depolarizing noise on 
an arbtitrary subset of k qubits.

However, this definition leads to 2^k Kraus operators in the unitary channel 
and is hence fairly slow to implement (unless k=n). For this reason QuEST 
only provides the one and two-qubit depolarizing channels. See [here](https://quest-kit.github.io/QuEST/group__decoherence.html)

For this reason, I would suggest keeping the global depolarizing channel as it 
is currently defined and add a function 
```julia
function single_qubit_depolarizing_channel(n, loc, p)
    return pauli_error_channel(n, loc, px=p/3, py=p/3, pz=p/3)
end
```
and a similarly defined `two_qubit_depolarizing_channel(n, locs, p)`.

2023-02-14 16:30 UTC, Roger-luo commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
@GiggleLiu Does this sound good?

2023-02-14 17:32 UTC, GiggleLiu commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
Yes, it makes sense. 👍🏾

2023-02-14 19:20 UTC, Roger-luo commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
Ok now if we agree on this, probably just go ahead fork my branch to put your proposal in. I can review it. Thanks! @jlbosse

2023-02-14 19:44 UTC, jlbosse commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
Will do! And is the debate about type piracy and where to put DensityMatrix resolved in the current version?

2023-02-15 21:05 UTC, Roger-luo commented on lib/YaoBlocks/src/channel/error.jl
> +    regscale!(dm, 1 - ch.p)
I think given now in 1.9 native code caching, we need and should eliminate type piracy and more specifically invalidations as much as possible to utilize native code caching. But we can do that in a separate PR. Just go ahead to include this first.

2023-03-09 11:27 UTC, closed without merging