fix issue 432
QuantumBFS/Yao.jl pull request #435
Opened 2022-10-28 03:27 UTC by GiggleLiu

## Change List
* New exported API `sandwich` in YaoBlocks for computing `<bra| op |ket>`.
* `expect` function now returns real and errors on complex values.
* The multiplication `<bra| * |ket>` now returns a number, and throws an error if the qubit number does not match.

2022-10-28 16:44 UTC, Roger-luo requested changes
LGTM in general, only minor changes is needed.

2022-10-28 16:44 UTC, Roger-luo commented on lib/YaoArrayRegister/src/operations.jl
> +    nqudits(bra) == nqudits(ket) && nremain(bra) == nremain(ket) || error(
do you remember what was the use case for contracting active qubits only? it seems losing functionality if we let this error

2022-10-28 16:44 UTC, Roger-luo commented on lib/YaoArrayRegister/src/operations.jl
> +    res
```suggestion
    res = zeros(eltype(promote_type(T1, T2)), nbatch(ket))
    for j in 1:size(A, 2), i in 1:size(A, 1)
        @inbounds res[i] += conj(A[i, j]) * C[i, j]
    end
    return res
```

2022-10-28 16:44 UTC, Roger-luo commented on lib/YaoBlocks/src/utils.jl
> +    if !(iszero(img) || isapprox(x - im*img, x))
why not just `isapprox(img, zero(img))`? It covers both cases (exact zero or approx zero)

also this line is not tested.

2022-10-28 16:44 UTC, Roger-luo commented on lib/YaoBlocks/src/utils.jl
> +        error("Can not convert number $x to real due to its large imaginary part.")
this should be an `InexactError` and the name of this function should be `approx_real`? `safe_real` sounds more like those `unsafe_xxx` families in `Base` or for integers.

2022-10-28 16:45 UTC, Roger-luo commented on lib/YaoArrayRegister/src/operations.jl
> +    nqudits(bra) == nqudits(ket) && nremain(bra) == nremain(ket) || error(
or there should be a `contract` function that always return a `Matrix`.

2022-10-29 04:27 UTC, GiggleLiu commented on lib/YaoBlocks/src/utils.jl
> +    if !(iszero(img) || isapprox(x - im*img, x))
This is a bit tricky. I want to support float, complex and Basic types.
`isapprox(img, zero(img))` is also too strict because there can be small imaginary part for real numbers.

2022-10-29 04:29 UTC, GiggleLiu commented on lib/YaoBlocks/src/utils.jl
> +    if !(iszero(img) || isapprox(x - im*img, x))
Wield, I can not see which line is not covered from the files tab.

2022-10-29 04:29 UTC, GiggleLiu commented on lib/YaoBlocks/src/utils.jl
> +        error("Can not convert number $x to real due to its large imaginary part.")
Sounds good

2022-10-29 04:32 UTC, GiggleLiu commented on lib/YaoArrayRegister/src/operations.jl
> +    nqudits(bra) == nqudits(ket) && nremain(bra) == nremain(ket) || error(
It is not intuitive to return a matrix, because it is hard to explain to users.
If we need it as a developer, we can use `state(bra) * state(ket)` directly.
Here, I prefer to make it simple. Either error on not fully activated registers, or not distinguishing on active and remaining qubits.

2022-10-29 23:59 UTC, Roger-luo commented on lib/YaoArrayRegister/src/operations.jl
> +    nqudits(bra) == nqudits(ket) && nremain(bra) == nremain(ket) || error(
Yeah I think just using `state` makes sense.

2022-10-30 00:00 UTC, Roger-luo commented on lib/YaoBlocks/src/utils.jl
> +    if !(iszero(img) || isapprox(x - im*img, x))
Do you have an example case that `isapprox(x, zero(x))` fails? It's not very intuitive to me that there's a difference between these two implementations.

2024-04-10 05:22 UTC, GiggleLiu commented
I think this PR should be merged. Automatic differentiating complex numbers does not make sense.

2024-04-10 05:23 UTC, GiggleLiu commented on lib/YaoBlocks/src/utils.jl
> +    if !(iszero(img) || isapprox(x - im*img, x))
`eps(0.0)` is too small.

```julia
julia> isapprox(imag(1+1e-17im), 0.0)
false

julia> eps(0.0)
5.0e-324
```

2024-04-11 14:55 UTC, Roger-luo approved these changes

2024-04-12 03:22 UTC, merged